import "./App.css";
import PostsComponent from "./PostsComponent";

const posts = [
  {
    userId: 1,
    id: 1,
    title:
      "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
    body: "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
  },
  {
    userId: 1,
    id: 2,
    title: "qui est esse",
    body: "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla",
  },
  {
    userId: 1,
    id: 3,
    title: "ea molestias quasi exercitationem repellat qui ipsa sit aut",
    body: "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut",
  },
  {
    userId: 1,
    id: 4,
    title: "eum et est occaecati",
    body: "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit",
  },
  {
    userId: 1,
    id: 5,
    title: "nesciunt quas odio",
    body: "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque",
  },
  {
    userId: 1,
    id: 6,
    title: "dolorem eum magni eos aperiam quia",
    body: "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae",
  },
  {
    userId: 1,
    id: 7,
    title: "magnam facilis autem",
    body: "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas",
  },
  {
    userId: 1,
    id: 8,
    title: "dolorem dolore est ipsam",
    body: "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae",
  },
  {
    userId: 1,
    id: 9,
    title: "nesciunt iure omnis dolorem tempora et accusantium",
    body: "consectetur animi nesciunt iure dolore\nenim quia ad\nveniam autem ut quam aut nobis\net est aut quod aut provident voluptas autem voluptas",
  },
  {
    userId: 1,
    id: 10,
    title: "optio molestias id quia eum",
    body: "quo et expedita modi cum officia vel magni\ndoloribus qui repudiandae\nvero nisi sit\nquos veniam quod sed accusamus veritatis error",
  },
  {
    userId: 2,
    id: 11,
    title: "et ea vero quia laudantium autem",
    body: "delectus reiciendis molestiae occaecati non minima eveniet qui voluptatibus\naccusamus in eum beatae sit\nvel qui neque voluptates ut commodi qui incidunt\nut animi commodi",
  },
  {
    userId: 2,
    id: 12,
    title: "in quibusdam tempore odit est dolorem",
    body: "itaque id aut magnam\npraesentium quia et ea odit et ea voluptas et\nsapiente quia nihil amet occaecati quia id voluptatem\nincidunt ea est distinctio odio",
  },
  {
    userId: 2,
    id: 13,
    title: "dolorum ut in voluptas mollitia et saepe quo animi",
    body: "aut dicta possimus sint mollitia voluptas commodi quo doloremque\niste corrupti reiciendis voluptatem eius rerum\nsit cumque quod eligendi laborum minima\nperferendis recusandae assumenda consectetur porro architecto ipsum ipsam",
  },
  {
    userId: 2,
    id: 14,
    title: "voluptatem eligendi optio",
    body: "fuga et accusamus dolorum perferendis illo voluptas\nnon doloremque neque facere\nad qui dolorum molestiae beatae\nsed aut voluptas totam sit illum",
  },
  {
    userId: 2,
    id: 15,
    title: "eveniet quod temporibus",
    body: "reprehenderit quos placeat\nvelit minima officia dolores impedit repudiandae molestiae nam\nvoluptas recusandae quis delectus\nofficiis harum fugiat vitae",
  },
  {
    userId: 2,
    id: 16,
    title:
      "sint suscipit perspiciatis velit dolorum rerum ipsa laboriosam odio",
    body: "suscipit nam nisi quo aperiam aut\nasperiores eos fugit maiores voluptatibus quia\nvoluptatem quis ullam qui in alias quia est\nconsequatur magni mollitia accusamus ea nisi voluptate dicta",
  },
  {
    userId: 2,
    id: 17,
    title: "fugit voluptas sed molestias voluptatem provident",
    body: "eos voluptas et aut odit natus earum\naspernatur fuga molestiae ullam\ndeserunt ratione qui eos\nqui nihil ratione nemo velit ut aut id quo",
  },
  {
    userId: 2,
    id: 18,
    title: "voluptate et itaque vero tempora molestiae",
    body: "eveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluptatem vel debitis et magnam",
  },
  {
    userId: 2,
    id: 19,
    title: "adipisci placeat illum aut reiciendis qui",
    body: "illum quis cupiditate provident sit magnam\nea sed aut omnis\nveniam maiores ullam consequatur atque\nadipisci quo iste expedita sit quos voluptas",
  },
  {
    userId: 2,
    id: 20,
    title: "doloribus ad provident suscipit at",
    body: "qui consequuntur ducimus possimus quisquam amet similique\nsuscipit porro ipsam amet\neos veritatis officiis exercitationem vel fugit aut necessitatibus totam\nomnis rerum consequatur expedita quidem cumque explicabo",
  },
  {
    userId: 3,
    id: 21,
    title: "asperiores ea ipsam voluptatibus modi minima quia sint",
    body: "repellat aliquid praesentium dolorem quo\nsed totam minus non itaque\nnihil labore molestiae sunt dolor eveniet hic recusandae veniam\ntempora et tenetur expedita sunt",
  },
  {
    userId: 3,
    id: 22,
    title: "dolor sint quo a velit explicabo quia nam",
    body: "eos qui et ipsum ipsam suscipit aut\nsed omnis non odio\nexpedita earum mollitia molestiae aut atque rem suscipit\nnam impedit esse",
  },
  {
    userId: 3,
    id: 23,
    title: "maxime id vitae nihil numquam",
    body: "veritatis unde neque eligendi\nquae quod architecto quo neque vitae\nest illo sit tempora doloremque fugit quod\net et vel beatae sequi ullam sed tenetur perspiciatis",
  },
  {
    userId: 3,
    id: 24,
    title: "autem hic labore sunt dolores incidunt",
    body: "enim et ex nulla\nomnis voluptas quia qui\nvoluptatem consequatur numquam aliquam sunt\ntotam recusandae id dignissimos aut sed asperiores deserunt",
  },
  {
    userId: 3,
    id: 25,
    title: "rem alias distinctio quo quis",
    body: "ullam consequatur ut\nomnis quis sit vel consequuntur\nipsa eligendi ipsum molestiae et omnis error nostrum\nmolestiae illo tempore quia et distinctio",
  },
  {
    userId: 3,
    id: 26,
    title: "est et quae odit qui non",
    body: "similique esse doloribus nihil accusamus\nomnis dolorem fuga consequuntur reprehenderit fugit recusandae temporibus\nperspiciatis cum ut laudantium\nomnis aut molestiae vel vero",
  },
  {
    userId: 3,
    id: 27,
    title: "quasi id et eos tenetur aut quo autem",
    body: "eum sed dolores ipsam sint possimus debitis occaecati\ndebitis qui qui et\nut placeat enim earum aut odit facilis\nconsequatur suscipit necessitatibus rerum sed inventore temporibus consequatur",
  },
  {
    userId: 3,
    id: 28,
    title: "delectus ullam et corporis nulla voluptas sequi",
    body: "non et quaerat ex quae ad maiores\nmaiores recusandae totam aut blanditiis mollitia quas illo\nut voluptatibus voluptatem\nsimilique nostrum eum",
  },
  {
    userId: 3,
    id: 29,
    title: "iusto eius quod necessitatibus culpa ea",
    body: "odit magnam ut saepe sed non qui\ntempora atque nihil\naccusamus illum doloribus illo dolor\neligendi repudiandae odit magni similique sed cum maiores",
  },
  {
    userId: 3,
    id: 30,
    title: "a quo magni similique perferendis",
    body: "alias dolor cumque\nimpedit blanditiis non eveniet odio maxime\nblanditiis amet eius quis tempora quia autem rem\na provident perspiciatis quia",
  },
  {
    userId: 4,
    id: 31,
    title: "ullam ut quidem id aut vel consequuntur",
    body: "debitis eius sed quibusdam non quis consectetur vitae\nimpedit ut qui consequatur sed aut in\nquidem sit nostrum et maiores adipisci atque\nquaerat voluptatem adipisci repudiandae",
  },
  {
    userId: 4,
    id: 32,
    title: "doloremque illum aliquid sunt",
    body: "deserunt eos nobis asperiores et hic\nest debitis repellat molestiae optio\nnihil ratione ut eos beatae quibusdam distinctio maiores\nearum voluptates et aut adipisci ea maiores voluptas maxime",
  },
  {
    userId: 4,
    id: 33,
    title: "qui explicabo molestiae dolorem",
    body: "rerum ut et numquam laborum odit est sit\nid qui sint in\nquasi tenetur tempore aperiam et quaerat qui in\nrerum officiis sequi cumque quod",
  },
  {
    userId: 4,
    id: 34,
    title: "magnam ut rerum iure",
    body: "ea velit perferendis earum ut voluptatem voluptate itaque iusto\ntotam pariatur in\nnemo voluptatem voluptatem autem magni tempora minima in\nest distinctio qui assumenda accusamus dignissimos officia nesciunt nobis",
  },
  {
    userId: 4,
    id: 35,
    title: "id nihil consequatur molestias animi provident",
    body: "nisi error delectus possimus ut eligendi vitae\nplaceat eos harum cupiditate facilis reprehenderit voluptatem beatae\nmodi ducimus quo illum voluptas eligendi\net nobis quia fugit",
  },
  {
    userId: 4,
    id: 36,
    title: "fuga nam accusamus voluptas reiciendis itaque",
    body: "ad mollitia et omnis minus architecto odit\nvoluptas doloremque maxime aut non ipsa qui alias veniam\nblanditiis culpa aut quia nihil cumque facere et occaecati\nqui aspernatur quia eaque ut aperiam inventore",
  },
  {
    userId: 4,
    id: 37,
    title: "provident vel ut sit ratione est",
    body: "debitis et eaque non officia sed nesciunt pariatur vel\nvoluptatem iste vero et ea\nnumquam aut expedita ipsum nulla in\nvoluptates omnis consequatur aut enim officiis in quam qui",
  },
  {
    userId: 4,
    id: 38,
    title: "explicabo et eos deleniti nostrum ab id repellendus",
    body: "animi esse sit aut sit nesciunt assumenda eum voluptas\nquia voluptatibus provident quia necessitatibus ea\nrerum repudiandae quia voluptatem delectus fugit aut id quia\nratione optio eos iusto veniam iure",
  },
  {
    userId: 4,
    id: 39,
    title: "eos dolorem iste accusantium est eaque quam",
    body: "corporis rerum ducimus vel eum accusantium\nmaxime aspernatur a porro possimus iste omnis\nest in deleniti asperiores fuga aut\nvoluptas sapiente vel dolore minus voluptatem incidunt ex",
  },
  {
    userId: 4,
    id: 40,
    title: "enim quo cumque",
    body: "ut voluptatum aliquid illo tenetur nemo sequi quo facilis\nipsum rem optio mollitia quas\nvoluptatem eum voluptas qui\nunde omnis voluptatem iure quasi maxime voluptas nam",
  },
  {
    userId: 5,
    id: 41,
    title: "non est facere",
    body: "molestias id nostrum\nexcepturi molestiae dolore omnis repellendus quaerat saepe\nconsectetur iste quaerat tenetur asperiores accusamus ex ut\nnam quidem est ducimus sunt debitis saepe",
  },
  {
    userId: 5,
    id: 42,
    title:
      "commodi ullam sint et excepturi error explicabo praesentium voluptas",
    body: "odio fugit voluptatum ducimus earum autem est incidunt voluptatem\nodit reiciendis aliquam sunt sequi nulla dolorem\nnon facere repellendus voluptates quia\nratione harum vitae ut",
  },
  {
    userId: 5,
    id: 43,
    title:
      "eligendi iste nostrum consequuntur adipisci praesentium sit beatae perferendis",
    body: "similique fugit est\nillum et dolorum harum et voluptate eaque quidem\nexercitationem quos nam commodi possimus cum odio nihil nulla\ndolorum exercitationem magnam ex et a et distinctio debitis",
  },
  {
    userId: 5,
    id: 44,
    title: "optio dolor molestias sit",
    body: "temporibus est consectetur dolore\net libero debitis vel velit laboriosam quia\nipsum quibusdam qui itaque fuga rem aut\nea et iure quam sed maxime ut distinctio quae",
  },
  {
    userId: 5,
    id: 45,
    title: "ut numquam possimus omnis eius suscipit laudantium iure",
    body: "est natus reiciendis nihil possimus aut provident\nex et dolor\nrepellat pariatur est\nnobis rerum repellendus dolorem autem",
  },
  {
    userId: 5,
    id: 46,
    title: "aut quo modi neque nostrum ducimus",
    body: "voluptatem quisquam iste\nvoluptatibus natus officiis facilis dolorem\nquis quas ipsam\nvel et voluptatum in aliquid",
  },
  {
    userId: 5,
    id: 47,
    title: "quibusdam cumque rem aut deserunt",
    body: "voluptatem assumenda ut qui ut cupiditate aut impedit veniam\noccaecati nemo illum voluptatem laudantium\nmolestiae beatae rerum ea iure soluta nostrum\neligendi et voluptate",
  },
  {
    userId: 5,
    id: 48,
    title: "ut voluptatem illum ea doloribus itaque eos",
    body: "voluptates quo voluptatem facilis iure occaecati\nvel assumenda rerum officia et\nillum perspiciatis ab deleniti\nlaudantium repellat ad ut et autem reprehenderit",
  },
  {
    userId: 5,
    id: 49,
    title: "laborum non sunt aut ut assumenda perspiciatis voluptas",
    body: "inventore ab sint\nnatus fugit id nulla sequi architecto nihil quaerat\neos tenetur in in eum veritatis non\nquibusdam officiis aspernatur cumque aut commodi aut",
  },
  {
    userId: 5,
    id: 50,
    title:
      "repellendus qui recusandae incidunt voluptates tenetur qui omnis exercitationem",
    body: "error suscipit maxime adipisci consequuntur recusandae\nvoluptas eligendi et est et voluptates\nquia distinctio ab amet quaerat molestiae et vitae\nadipisci impedit sequi nesciunt quis consectetur",
  },
  {
    userId: 6,
    id: 51,
    title: "soluta aliquam aperiam consequatur illo quis voluptas",
    body: "sunt dolores aut doloribus\ndolore doloribus voluptates tempora et\ndoloremque et quo\ncum asperiores sit consectetur dolorem",
  },
  {
    userId: 6,
    id: 52,
    title: "qui enim et consequuntur quia animi quis voluptate quibusdam",
    body: "iusto est quibusdam fuga quas quaerat molestias\na enim ut sit accusamus enim\ntemporibus iusto accusantium provident architecto\nsoluta esse reprehenderit qui laborum",
  },
  {
    userId: 6,
    id: 53,
    title: "ut quo aut ducimus alias",
    body: "minima harum praesentium eum rerum illo dolore\nquasi exercitationem rerum nam\nporro quis neque quo\nconsequatur minus dolor quidem veritatis sunt non explicabo similique",
  },
  {
    userId: 6,
    id: 54,
    title: "sit asperiores ipsam eveniet odio non quia",
    body: "totam corporis dignissimos\nvitae dolorem ut occaecati accusamus\nex velit deserunt\net exercitationem vero incidunt corrupti mollitia",
  },
  {
    userId: 6,
    id: 55,
    title: "sit vel voluptatem et non libero",
    body: "debitis excepturi ea perferendis harum libero optio\neos accusamus cum fuga ut sapiente repudiandae\net ut incidunt omnis molestiae\nnihil ut eum odit",
  },
  {
    userId: 6,
    id: 56,
    title: "qui et at rerum necessitatibus",
    body: "aut est omnis dolores\nneque rerum quod ea rerum velit pariatur beatae excepturi\net provident voluptas corrupti\ncorporis harum reprehenderit dolores eligendi",
  },
  {
    userId: 6,
    id: 57,
    title: "sed ab est est",
    body: "at pariatur consequuntur earum quidem\nquo est laudantium soluta voluptatem\nqui ullam et est\net cum voluptas voluptatum repellat est",
  },
  {
    userId: 6,
    id: 58,
    title: "voluptatum itaque dolores nisi et quasi",
    body: "veniam voluptatum quae adipisci id\net id quia eos ad et dolorem\naliquam quo nisi sunt eos impedit error\nad similique veniam",
  },
  {
    userId: 6,
    id: 59,
    title: "qui commodi dolor at maiores et quis id accusantium",
    body: "perspiciatis et quam ea autem temporibus non voluptatibus qui\nbeatae a earum officia nesciunt dolores suscipit voluptas et\nanimi doloribus cum rerum quas et magni\net hic ut ut commodi expedita sunt",
  },
  {
    userId: 6,
    id: 60,
    title:
      "consequatur placeat omnis quisquam quia reprehenderit fugit veritatis facere",
    body: "asperiores sunt ab assumenda cumque modi velit\nqui esse omnis\nvoluptate et fuga perferendis voluptas\nillo ratione amet aut et omnis",
  },
  {
    userId: 7,
    id: 61,
    title: "voluptatem doloribus consectetur est ut ducimus",
    body: "ab nemo optio odio\ndelectus tenetur corporis similique nobis repellendus rerum omnis facilis\nvero blanditiis debitis in nesciunt doloribus dicta dolores\nmagnam minus velit",
  },
  {
    userId: 7,
    id: 62,
    title: "beatae enim quia vel",
    body: "enim aspernatur illo distinctio quae praesentium\nbeatae alias amet delectus qui voluptate distinctio\nodit sint accusantium autem omnis\nquo molestiae omnis ea eveniet optio",
  },
  {
    userId: 7,
    id: 63,
    title:
      "voluptas blanditiis repellendus animi ducimus error sapiente et suscipit",
    body: "enim adipisci aspernatur nemo\nnumquam omnis facere dolorem dolor ex quis temporibus incidunt\nab delectus culpa quo reprehenderit blanditiis asperiores\naccusantium ut quam in voluptatibus voluptas ipsam dicta",
  },
  {
    userId: 7,
    id: 64,
    title: "et fugit quas eum in in aperiam quod",
    body: "id velit blanditiis\neum ea voluptatem\nmolestiae sint occaecati est eos perspiciatis\nincidunt a error provident eaque aut aut qui",
  },
  {
    userId: 7,
    id: 65,
    title: "consequatur id enim sunt et et",
    body: "voluptatibus ex esse\nsint explicabo est aliquid cumque adipisci fuga repellat labore\nmolestiae corrupti ex saepe at asperiores et perferendis\nnatus id esse incidunt pariatur",
  },
  {
    userId: 7,
    id: 66,
    title: "repudiandae ea animi iusto",
    body: "officia veritatis tenetur vero qui itaque\nsint non ratione\nsed et ut asperiores iusto eos molestiae nostrum\nveritatis quibusdam et nemo iusto saepe",
  },
  {
    userId: 7,
    id: 67,
    title: "aliquid eos sed fuga est maxime repellendus",
    body: "reprehenderit id nostrum\nvoluptas doloremque pariatur sint et accusantium quia quod aspernatur\net fugiat amet\nnon sapiente et consequatur necessitatibus molestiae",
  },
  {
    userId: 7,
    id: 68,
    title: "odio quis facere architecto reiciendis optio",
    body: "magnam molestiae perferendis quisquam\nqui cum reiciendis\nquaerat animi amet hic inventore\nea quia deleniti quidem saepe porro velit",
  },
  {
    userId: 7,
    id: 69,
    title: "fugiat quod pariatur odit minima",
    body: "officiis error culpa consequatur modi asperiores et\ndolorum assumenda voluptas et vel qui aut vel rerum\nvoluptatum quisquam perspiciatis quia rerum consequatur totam quas\nsequi commodi repudiandae asperiores et saepe a",
  },
  {
    userId: 7,
    id: 70,
    title: "voluptatem laborum magni",
    body: "sunt repellendus quae\nest asperiores aut deleniti esse accusamus repellendus quia aut\nquia dolorem unde\neum tempora esse dolore",
  },
  {
    userId: 8,
    id: 71,
    title: "et iusto veniam et illum aut fuga",
    body: "occaecati a doloribus\niste saepe consectetur placeat eum voluptate dolorem et\nqui quo quia voluptas\nrerum ut id enim velit est perferendis",
  },
  {
    userId: 8,
    id: 72,
    title: "sint hic doloribus consequatur eos non id",
    body: "quam occaecati qui deleniti consectetur\nconsequatur aut facere quas exercitationem aliquam hic voluptas\nneque id sunt ut aut accusamus\nsunt consectetur expedita inventore velit",
  },
  {
    userId: 8,
    id: 73,
    title: "consequuntur deleniti eos quia temporibus ab aliquid at",
    body: "voluptatem cumque tenetur consequatur expedita ipsum nemo quia explicabo\naut eum minima consequatur\ntempore cumque quae est et\net in consequuntur voluptatem voluptates aut",
  },
  {
    userId: 8,
    id: 74,
    title: "enim unde ratione doloribus quas enim ut sit sapiente",
    body: "odit qui et et necessitatibus sint veniam\nmollitia amet doloremque molestiae commodi similique magnam et quam\nblanditiis est itaque\nquo et tenetur ratione occaecati molestiae tempora",
  },
  {
    userId: 8,
    id: 75,
    title: "dignissimos eum dolor ut enim et delectus in",
    body: "commodi non non omnis et voluptas sit\nautem aut nobis magnam et sapiente voluptatem\net laborum repellat qui delectus facilis temporibus\nrerum amet et nemo voluptate expedita adipisci error dolorem",
  },
  {
    userId: 8,
    id: 76,
    title: "doloremque officiis ad et non perferendis",
    body: "ut animi facere\ntotam iusto tempore\nmolestiae eum aut et dolorem aperiam\nquaerat recusandae totam odio",
  },
  {
    userId: 8,
    id: 77,
    title: "necessitatibus quasi exercitationem odio",
    body: "modi ut in nulla repudiandae dolorum nostrum eos\naut consequatur omnis\nut incidunt est omnis iste et quam\nvoluptates sapiente aliquam asperiores nobis amet corrupti repudiandae provident",
  },
  {
    userId: 8,
    id: 78,
    title: "quam voluptatibus rerum veritatis",
    body: "nobis facilis odit tempore cupiditate quia\nassumenda doloribus rerum qui ea\nillum et qui totam\naut veniam repellendus",
  },
  {
    userId: 8,
    id: 79,
    title: "pariatur consequatur quia magnam autem omnis non amet",
    body: "libero accusantium et et facere incidunt sit dolorem\nnon excepturi qui quia sed laudantium\nquisquam molestiae ducimus est\nofficiis esse molestiae iste et quos",
  },
  {
    userId: 8,
    id: 80,
    title: "labore in ex et explicabo corporis aut quas",
    body: "ex quod dolorem ea eum iure qui provident amet\nquia qui facere excepturi et repudiandae\nasperiores molestias provident\nminus incidunt vero fugit rerum sint sunt excepturi provident",
  },
  {
    userId: 9,
    id: 81,
    title: "tempora rem veritatis voluptas quo dolores vero",
    body: "facere qui nesciunt est voluptatum voluptatem nisi\nsequi eligendi necessitatibus ea at rerum itaque\nharum non ratione velit laboriosam quis consequuntur\nex officiis minima doloremque voluptas ut aut",
  },
  {
    userId: 9,
    id: 82,
    title: "laudantium voluptate suscipit sunt enim enim",
    body: "ut libero sit aut totam inventore sunt\nporro sint qui sunt molestiae\nconsequatur cupiditate qui iste ducimus adipisci\ndolor enim assumenda soluta laboriosam amet iste delectus hic",
  },
  {
    userId: 9,
    id: 83,
    title: "odit et voluptates doloribus alias odio et",
    body: "est molestiae facilis quis tempora numquam nihil qui\nvoluptate sapiente consequatur est qui\nnecessitatibus autem aut ipsa aperiam modi dolore numquam\nreprehenderit eius rem quibusdam",
  },
  {
    userId: 9,
    id: 84,
    title:
      "optio ipsam molestias necessitatibus occaecati facilis veritatis dolores aut",
    body: "sint molestiae magni a et quos\neaque et quasi\nut rerum debitis similique veniam\nrecusandae dignissimos dolor incidunt consequatur odio",
  },
  {
    userId: 9,
    id: 85,
    title: "dolore veritatis porro provident adipisci blanditiis et sunt",
    body: "similique sed nisi voluptas iusto omnis\nmollitia et quo\nassumenda suscipit officia magnam sint sed tempora\nenim provident pariatur praesentium atque animi amet ratione",
  },
  {
    userId: 9,
    id: 86,
    title: "placeat quia et porro iste",
    body: "quasi excepturi consequatur iste autem temporibus sed molestiae beatae\net quaerat et esse ut\nvoluptatem occaecati et vel explicabo autem\nasperiores pariatur deserunt optio",
  },
  {
    userId: 9,
    id: 87,
    title: "nostrum quis quasi placeat",
    body: "eos et molestiae\nnesciunt ut a\ndolores perspiciatis repellendus repellat aliquid\nmagnam sint rem ipsum est",
  },
  {
    userId: 9,
    id: 88,
    title: "sapiente omnis fugit eos",
    body: "consequatur omnis est praesentium\nducimus non iste\nneque hic deserunt\nvoluptatibus veniam cum et rerum sed",
  },
  {
    userId: 9,
    id: 89,
    title: "sint soluta et vel magnam aut ut sed qui",
    body: "repellat aut aperiam totam temporibus autem et\narchitecto magnam ut\nconsequatur qui cupiditate rerum quia soluta dignissimos nihil iure\ntempore quas est",
  },
  {
    userId: 9,
    id: 90,
    title: "ad iusto omnis odit dolor voluptatibus",
    body: "minus omnis soluta quia\nqui sed adipisci voluptates illum ipsam voluptatem\neligendi officia ut in\neos soluta similique molestias praesentium blanditiis",
  },
  {
    userId: 10,
    id: 91,
    title: "aut amet sed",
    body: "libero voluptate eveniet aperiam sed\nsunt placeat suscipit molestias\nsimilique fugit nam natus\nexpedita consequatur consequatur dolores quia eos et placeat",
  },
  {
    userId: 10,
    id: 92,
    title: "ratione ex tenetur perferendis",
    body: "aut et excepturi dicta laudantium sint rerum nihil\nlaudantium et at\na neque minima officia et similique libero et\ncommodi voluptate qui",
  },
  {
    userId: 10,
    id: 93,
    title: "beatae soluta recusandae",
    body: "dolorem quibusdam ducimus consequuntur dicta aut quo laboriosam\nvoluptatem quis enim recusandae ut sed sunt\nnostrum est odit totam\nsit error sed sunt eveniet provident qui nulla",
  },
  {
    userId: 10,
    id: 94,
    title: "qui qui voluptates illo iste minima",
    body: "aspernatur expedita soluta quo ab ut similique\nexpedita dolores amet\nsed temporibus distinctio magnam saepe deleniti\nomnis facilis nam ipsum natus sint similique omnis",
  },
  {
    userId: 10,
    id: 95,
    title: "id minus libero illum nam ad officiis",
    body: "earum voluptatem facere provident blanditiis velit laboriosam\npariatur accusamus odio saepe\ncumque dolor qui a dicta ab doloribus consequatur omnis\ncorporis cupiditate eaque assumenda ad nesciunt",
  },
  {
    userId: 10,
    id: 96,
    title: "quaerat velit veniam amet cupiditate aut numquam ut sequi",
    body: "in non odio excepturi sint eum\nlabore voluptates vitae quia qui et\ninventore itaque rerum\nveniam non exercitationem delectus aut",
  },
  {
    userId: 10,
    id: 97,
    title: "quas fugiat ut perspiciatis vero provident",
    body: "eum non blanditiis soluta porro quibusdam voluptas\nvel voluptatem qui placeat dolores qui velit aut\nvel inventore aut cumque culpa explicabo aliquid at\nperspiciatis est et voluptatem dignissimos dolor itaque sit nam",
  },
  {
    userId: 10,
    id: 98,
    title: "laboriosam dolor voluptates",
    body: "doloremque ex facilis sit sint culpa\nsoluta assumenda eligendi non ut eius\nsequi ducimus vel quasi\nveritatis est dolores",
  },
  {
    userId: 10,
    id: 99,
    title: "temporibus sit alias delectus eligendi possimus magni",
    body: "quo deleniti praesentium dicta non quod\naut est molestias\nmolestias et officia quis nihil\nitaque dolorem quia",
  },
  {
    userId: 10,
    id: 100,
    title: "at nam consequatur ea labore ea harum",
    body: "cupiditate quo est a modi nesciunt soluta\nipsa voluptas error itaque dicta in\nautem qui minus magnam et distinctio eum\naccusamus ratione error aut",
  },
];

const capsules = [
  {
    capsule_serial: "C101",
    capsule_id: "dragon1",
    status: "retired",
    original_launch: "2010-12-08T15:43:00.000Z",
    original_launch_unix: 1291822980,
    missions: [{ name: "COTS 1", flight: 7 }],
    landings: 1,
    type: "Dragon 1.0",
    details: "Reentered after three weeks in orbit",
    reuse_count: 0,
  },
  {
    capsule_serial: "C102",
    capsule_id: "dragon1",
    status: "retired",
    original_launch: "2012-05-22T07:44:00.000Z",
    original_launch_unix: 1335944640,
    missions: [{ name: "COTS 2", flight: 8 }],
    landings: 1,
    type: "Dragon 1.0",
    details: "First Dragon spacecraft",
    reuse_count: 0,
  },
  {
    capsule_serial: "C103",
    capsule_id: "dragon1",
    status: "unknown",
    original_launch: "2012-10-08T00:35:00.000Z",
    original_launch_unix: 1349656500,
    missions: [{ name: "CRS-1", flight: 9 }],
    landings: 1,
    type: "Dragon 1.0",
    details: "First of twenty missions flown under the CRS1 contract",
    reuse_count: 0,
  },
  {
    capsule_serial: "C104",
    capsule_id: "dragon1",
    status: "unknown",
    original_launch: "2013-03-01T19:10:00.000Z",
    original_launch_unix: 1362165000,
    missions: [{ name: "CRS-2", flight: 10 }],
    landings: 1,
    type: "Dragon 1.0",
    details: null,
    reuse_count: 0,
  },
  {
    capsule_serial: "C105",
    capsule_id: "dragon1",
    status: "unknown",
    original_launch: "2014-04-18T19:25:00.000Z",
    original_launch_unix: 1397849100,
    missions: [{ name: "CRS-3", flight: 14 }],
    landings: 1,
    type: "Dragon 1.1",
    details: "First Dragon v1.1 capsule",
    reuse_count: 0,
  },
  {
    capsule_serial: "C106",
    capsule_id: "dragon1",
    status: "active",
    original_launch: "2014-09-21T05:52:00.000Z",
    original_launch_unix: 1411278720,
    missions: [
      { name: "CRS-4", flight: 18 },
      { name: "CRS-11", flight: 41 },
      { name: "CRS-19", flight: 85 },
    ],
    landings: 3,
    type: "Dragon 1.1",
    details: "First Dragon capsule to be reused",
    reuse_count: 2,
  },
  {
    capsule_serial: "C107",
    capsule_id: "dragon1",
    status: "unknown",
    original_launch: "2015-01-10T09:47:00.000Z",
    original_launch_unix: 1420883220,
    missions: [{ name: "CRS-5", flight: 19 }],
    landings: 1,
    type: "Dragon 1.1",
    details: null,
    reuse_count: 0,
  },
  {
    capsule_serial: "C108",
    capsule_id: "dragon1",
    status: "active",
    original_launch: "2015-04-14T20:10:00.000Z",
    original_launch_unix: 1429042200,
    missions: [
      { name: "CRS-6", flight: 22 },
      { name: "CRS-13", flight: 51 },
      { name: "CRS-18", flight: 82 },
    ],
    landings: 3,
    type: "Dragon 1.1",
    details: "Second Dragon capsule to be reused",
    reuse_count: 2,
  },
  {
    capsule_serial: "C109",
    capsule_id: "dragon1",
    status: "destroyed",
    original_launch: "2015-06-28T14:21:00.000Z",
    original_launch_unix: 1435501260,
    missions: [{ name: "CRS-7", flight: 24 }],
    landings: 0,
    type: "Dragon 1.1",
    details: "Destroyed on impact after F9 launch failure",
    reuse_count: 0,
  },
  {
    capsule_serial: "C110",
    capsule_id: "dragon1",
    status: "active",
    original_launch: "2016-04-08T20:43:00.000Z",
    original_launch_unix: 1460148180,
    missions: [
      { name: "CRS-8", flight: 28 },
      { name: "CRS-14", flight: 59 },
    ],
    landings: 2,
    type: "Dragon 1.1",
    details: null,
    reuse_count: 1,
  },
  {
    capsule_serial: "C111",
    capsule_id: "dragon1",
    status: "active",
    original_launch: "2016-07-18T04:45:00.000Z",
    original_launch_unix: 1468817100,
    missions: [
      { name: "CRS-9", flight: 32 },
      { name: "CRS-15", flight: 64 },
    ],
    landings: 2,
    type: "Dragon 1.1",
    details: null,
    reuse_count: 1,
  },
  {
    capsule_serial: "C112",
    capsule_id: "dragon1",
    status: "active",
    original_launch: "2017-02-19T14:39:00.000Z",
    original_launch_unix: 1487515140,
    missions: [
      { name: "CRS-10", flight: 36 },
      { name: "CRS-16", flight: 72 },
      { name: "CRS-20", flight: 91 },
    ],
    landings: 3,
    type: "Dragon 1.1",
    details: null,
    reuse_count: 2,
  },
  {
    capsule_serial: "C113",
    capsule_id: "dragon1",
    status: "active",
    original_launch: "2017-08-14T16:31:00.000Z",
    original_launch_unix: 1502728260,
    missions: [
      { name: "CRS-12", flight: 45 },
      { name: "CRS-17", flight: 78 },
    ],
    landings: 2,
    type: "Dragon 1.1",
    details: "The last newly manufactured Dragon 1",
    reuse_count: 1,
  },
  {
    capsule_serial: "C201",
    capsule_id: "dragon2",
    status: "active",
    original_launch: "2019-03-02T07:45:00.000Z",
    original_launch_unix: 1551512700,
    missions: [{ name: "CCtCap Demo Mission 1", flight: 76 }],
    landings: 1,
    type: "Dragon 2.0",
    details: "Destroyed in a test anomaly at LZ-1 on April 20, 2019",
    reuse_count: 0,
  },
  {
    capsule_serial: "C205",
    capsule_id: "dragon2",
    status: "active",
    original_launch: "2020-01-19T14:00:00.000Z",
    original_launch_unix: 1579442400,
    missions: [{ name: "Crew Dragon In Flight Abort Test", flight: 88 }],
    landings: 1,
    type: "Dragon 2.0",
    details:
      "In construction for use in first mission in contract under the CCtCap contract",
    reuse_count: 0,
  },
  {
    capsule_serial: "C206",
    capsule_id: "dragon2",
    status: "active",
    original_launch: "2020-05-30T19:22:00.000Z",
    original_launch_unix: 1590866520,
    missions: [{ name: "CCtCap Demo Mission 2", flight: 94 }],
    landings: 1,
    type: "Dragon 2.0",
    details:
      "In Hawthorne, CA as of October 11, 2019. Seen in background during Musk/Bridenstine press conference.",
    reuse_count: 0,
  },
  {
    capsule_serial: "C202",
    capsule_id: "dragon2",
    status: "active",
    original_launch: null,
    original_launch_unix: null,
    missions: [],
    landings: 0,
    type: "Dragon 2.0",
    details:
      "Capsule used to qualify Dragon 2's environmental control and life support systems.",
    reuse_count: 0,
  },
  {
    capsule_serial: "C203",
    capsule_id: "dragon2",
    status: "active",
    original_launch: null,
    original_launch_unix: null,
    missions: [],
    landings: 0,
    type: "Dragon 2.0",
    details: "Rumored to be used for Inflight Abort Test after DM-1",
    reuse_count: 0,
  },
  {
    capsule_serial: "C204",
    capsule_id: "dragon2",
    status: "active",
    original_launch: null,
    original_launch_unix: null,
    missions: [],
    landings: 0,
    type: "Dragon 2.0",
    details: "Currently in construction for use in DM-2",
    reuse_count: 0,
  },
];

function App() {
  return (
    // Posts
    <div className="App">
      <h1>Posts</h1>
      <PostsComponent posts={posts} />
    </div>

    // Capsules
    // <div className="App">
    //   <h1>Posts</h1>
    //   <PostsComponent capsules={capsules} />
    // </div>
  );
}

export default App;
